# Generated by Django 6.0.3 on 2026-04-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_conge', models.CharField(choices=[('vacances', 'Vacances'), ('fete', 'Fête'), ('autre', 'Autre')], default='vacances', max_length=20, verbose_name='Type de congé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Congé/Holiday',
                'verbose_name_plural': 'Congés/Holidays',
                'ordering': ['date_debut'],
            },
        ),
    ]
